service: avaliador-scti

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: personal
  region: sa-east-1
  memorySize: 128
  timeout: 30

package:
  exclude:
    - .env.*
    - node_modules/**/aws-sdk/**
    - .git/**
    - .gitignore
    - tsconfig.json

functions:
  hello:
    handler: handler.hello
