service: avaliador-scti

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: personal
  region: sa-east-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action: '*'
      Resource: '*'

package:
  exclude:
    - example.env
    - node_modules/**/aws-sdk/**
    - .git/**
    - .gitignore
    - tsconfig.json

functions:
  hello:
    handler: build/index.hello
    events:
      - http:
          path: /
          method: get
          cors: true

  createWorkshop:
    handler: build/index.createWorkshop
    events:
      - http:
          path: /workshops
          method: post
          cors: true

  sendVerificationEmail:
    handler: build/index.sendVerificationEmail
    events:
      - sqs:
          arn: { Fn::GetAtt: [VerificationEmailQueue, Arn] }
          batchSize: 1

resources:
  Resources:
    VerificationEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: '${opt:stage}-verification-email-queue'
